
package entreprise;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MonService", targetNamespace = "http://entreprise/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MonService {


    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "methode", targetNamespace = "http://entreprise/", className = "entreprise.Methode")
    @ResponseWrapper(localName = "methodeResponse", targetNamespace = "http://entreprise/", className = "entreprise.MethodeResponse")
    @Action(input = "http://entreprise/MonService/methodeRequest", output = "http://entreprise/MonService/methodeResponse")
    public int methode();

}
