
package entreprise;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MonService", targetNamespace = "http://entreprise/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MonService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "maMethode", targetNamespace = "http://entreprise/", className = "entreprise.MaMethode")
    @ResponseWrapper(localName = "maMethodeResponse", targetNamespace = "http://entreprise/", className = "entreprise.MaMethodeResponse")
    @Action(input = "http://entreprise/MonService/maMethodeRequest", output = "http://entreprise/MonService/maMethodeResponse")
    public int maMethode(
        @WebParam(name = "arg0", targetNamespace = "")
        float arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
